services:

  backend:
    build:
      context: ./backend
    container_name: ecommerce_backend

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    restart: unless-stopped

    depends_on:
      - postgres

    networks:
      - ecommerce_network

  frontend:
    build:
      context: ./frontend
    container_name: ecommerce_frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    restart: unless-stopped

    networks:
      - ecommerce_network

  postgres:
    image: postgres:17-alpine
    container_name: ecommerce_postgres

    env_file:
          - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

    networks:
      - ecommerce_network

volumes:
  postgres_data:


networks:
  ecommerce_network: